GRANT SELECT ON regmdr.EMAIL_OUT TO CCPA; 

GRANT UPDATE ON regmdr.EMAIL_OUT TO CCPA;

GRANT SELECT ON regmdr.SOURCE_DATA_ELOQUA TO CCPA; 

GRANT UPDATE ON regmdr.SOURCE_DATA_ELOQUA TO CCPA;

GRANT SELECT ON regmdr.EMAIL_HYGIENE_RESULTS_HISTORY TO CCPA; 

GRANT UPDATE ON regmdr.EMAIL_HYGIENE_RESULTS_HISTORY TO CCPA;

GRANT SELECT ON regmdr.EMAIL_HYGIENE_RESULTS TO CCPA; 

GRANT UPDATE ON regmdr.EMAIL_HYGIENE_RESULTS TO CCPA;

GRANT SELECT ON regmdr.SOURCE_DATA TO CCPA; 

GRANT UPDATE ON regmdr.SOURCE_DATA TO CCPA;

GRANT SELECT ON regmdr.CONTACT_HISTORY TO CCPA; 

GRANT UPDATE ON regmdr.CONTACT_HISTORY TO CCPA;

GRANT SELECT ON regmdr.SOURCE_DATA_OPT TO CCPA; 

GRANT UPDATE ON regmdr.SOURCE_DATA_OPT TO CCPA;

GRANT SELECT ON regmdr.SOURCE_DATA_PAYER TO CCPA; 

GRANT UPDATE ON regmdr.SOURCE_DATA_PAYER TO CCPA;

GRANT SELECT ON regmdr.SOURCE_DATA_RAW TO CCPA; 

GRANT UPDATE ON regmdr.SOURCE_DATA_RAW TO CCPA;

GRANT SELECT ON regmdr.SOURCE_DATA_RAW_PAYER TO CCPA; 

GRANT UPDATE ON regmdr.SOURCE_DATA_RAW_PAYER TO CCPA;

GRANT SELECT ON regmdr.VENDOR_APPEND TO CCPA; 

GRANT UPDATE ON regmdr.VENDOR_APPEND TO CCPA;

GRANT SELECT ON regmdr.VENDOR_APPEND_HISTORY TO CCPA; 

GRANT UPDATE ON regmdr.VENDOR_APPEND_HISTORY TO CCPA;

GRANT SELECT ON regmdr.EMAIL_ACTIVITY TO CCPA; 

GRANT UPDATE ON regmdr.EMAIL_ACTIVITY TO CCPA;

GRANT SELECT ON regmdr.communication_contact TO CCPA; 

GRANT UPDATE ON regmdr.communication_contact TO CCPA;


