spool B_25226_rollback_regmdr.log

set echo on
set define off
set sqlblanklines on

DROP INDEX eo_email_idx; 

DROP INDEX add_email_idx; 

DROP INDEX radd_email_idx; 

DROP INDEX sd_email_idx; 

DROP INDEX CONTH_EMAIL_idx; 

DROP INDEX SDO_EMAIL_ADDRESS_idx; 

DROP INDEX sdp_email_idx; 

DROP INDEX sdr_email_idx; 

DROP INDEX sdrp_email_idx; 

DROP INDEX vapd_email_idx; 

DROP INDEX vapdh_email_idx; 

DROP INDEX ea_email_idx; 

REVOKE UPDATE ON regmdr.EMAIL_HYGIENE_RESULTS FROM CCPA;

REVOKE SELECT ON regmdr.SOURCE_DATA FROM CCPA; 

REVOKE UPDATE ON regmdr.SOURCE_DATA FROM CCPA;

REVOKE SELECT ON regmdr.CONTACT_HISTORY FROM CCPA; 

REVOKE UPDATE ON regmdr.CONTACT_HISTORY FROM CCPA;

REVOKE SELECT ON regmdr.SOURCE_DATA_OPT FROM CCPA; 

REVOKE UPDATE ON regmdr.SOURCE_DATA_OPT FROM CCPA;

REVOKE SELECT ON regmdr.SOURCE_DATA_PAYER FROM CCPA; 

REVOKE UPDATE ON regmdr.SOURCE_DATA_PAYER FROM CCPA;

REVOKE SELECT ON regmdr.SOURCE_DATA_RAW FROM CCPA; 

REVOKE UPDATE ON regmdr.SOURCE_DATA_RAW FROM CCPA;

REVOKE SELECT ON regmdr.SOURCE_DATA_RAW_PAYER FROM CCPA; 

REVOKE UPDATE ON regmdr.SOURCE_DATA_RAW_PAYER FROM CCPA;

REVOKE SELECT ON regmdr.VENDOR_APPEND FROM CCPA; 

REVOKE UPDATE ON regmdr.VENDOR_APPEND FROM CCPA;

REVOKE SELECT ON regmdr.VENDOR_APPEND_HISTORY FROM CCPA; 

REVOKE UPDATE ON regmdr.VENDOR_APPEND_HISTORY FROM CCPA;

REVOKE SELECT ON regmdr.EMAIL_ACTIVITY FROM CCPA; 

REVOKE UPDATE ON regmdr.EMAIL_ACTIVITY FROM CCPA;

REVOKE SELECT ON regmdr.communication_contact FROM CCPA; 

REVOKE UPDATE ON regmdr.communication_contact FROM CCPA;

show errors

spool off
