USE ANALYTICS_FORD;
DROP TABLE [ELOQUA_API_EMAIL_SEND];
DROP TABLE [ELOQUA_API_EMAIL_OPEN];
DROP TABLE [ELOQUA_API_EMAIL_CLICKTHROUGH];
DROP TABLE [ELOQUA_API_EMAIL_BOUNCEBACK];
DROP TABLE [ELOQUA_API_EMAIL_UNSUBSCRIBE];
DROP TABLE [ELOQUA_API_EMAIL_ATTRIBUTES];

USE Eloqua_Email_Activity;
DROP TABLE [ELOQUA_API_EMAIL_ACTIVITY_STAGE];