use cim_meta_stage_Db
go 

SELECT *
FROM CM_COMMUNICATION_COMM_PLAN CCP
JOIN CM_COMM_PLAN_STEP CPS
ON CCP.COMM_PLAN_ID = CPS.COMM_PLAN_ID
LEFT JOIN CM_STEP S
ON S.STEP_ID = CPS.STEP_ID
LEFT JOIN CM_STEP_MESSAGE CSM
ON S.STEP_ID = CSM.STEP_ID
LEFT JOIN CM_MESSAGE M
ON M.MESSAGE_ID = CSM.MESSAGE_ID
WHERE CCP.COMMUNICATION_ID = '2000GFFCD0JZ';

SELECT TSD.TEXT_VAL
FROM CR_COMPONENT_RENDER_MODEL CRM
JOIN CR_TEXT_STORAGE_DATA TSD
ON CRM.RENDER_MODEL_TEXT_ID = TSD.TEXT_STORAGE_ID
WHERE CRM.COMPONENT_ID = '2000GFFCD0JZ'
ORDER BY TSD.SEQUENCE_ORD;




SELECT * into TEMP_CM_COMM_PLAN_STEP_160909 FROM CM_COMM_PLAN_STEP WHERE COMM_PLAN_ID = '2000GFFCD0K4' AND STEP_ID = '2000ggv79rhr'
SELECT * into TEMP_CM_COMM_PLAN_MESSAGE_160909 FROM CM_COMM_PLAN_MESSAGE WHERE COMM_PLAN_ID = '2000GFFCD0K4' AND STEP_ID = '2000ggv79rhr'
select * into TEMP_CM_COMM_PACKAGE_PRESENTATION_160909 from dbo.CM_COMM_PACKAGE_PRESENTATION WHERE COMM_PLAN_ID = '2000GFFCD0K4' AND STEP_ID = '2000ggv79rhr'
select * into TEMP_cm_comm_package_160909 from cm_comm_package WHERE COMM_PLAN_ID = '2000GFFCD0K4' AND STEP_ID = '2000ggv79rhr'
select * into TEMP_cm_comm_package_collateral_160909 from cm_comm_package_collateral WHERE COMM_PLAN_ID = '2000GFFCD0K4' AND STEP_ID = '2000ggv79rhr'

select * from TEMP_CM_COMM_PLAN_STEP_160909
select * from TEMP_CM_COMM_PLAN_MESSAGE_160909
select * from TEMP_CM_COMM_PACKAGE_PRESENTATION_160909
select * from TEMP_cm_comm_package_160909
select * from TEMP_cm_comm_package_collateral_160909

--DELETE FROM CM_COMM_PLAN_STEP WHERE COMM_PLAN_ID = '2000GFFCD0K4' AND STEP_ID = '2000ggv79rhr'
--DELETE FROM CM_COMM_PLAN_MESSAGE WHERE COMM_PLAN_ID = '2000GFFCD0K4' AND STEP_ID = '2000ggv79rhr'

delete from cm_comm_package WHERE COMM_PLAN_ID = '2000GFFCD0K4' AND STEP_ID = '2000ggv79rhr'
delete from dbo.CM_COMM_PACKAGE_PRESENTATION WHERE COMM_PLAN_ID = '2000GFFCD0K4' AND STEP_ID = '2000ggv79rhr'
delete from cm_comm_package_collateral WHERE COMM_PLAN_ID = '2000GFFCD0K4' AND STEP_ID = '2000ggv79rhr'



select * from cm_comm_package WHERE COMM_PLAN_ID = '2000GFFCD0K4' AND STEP_ID = '2000ggv79rhr'
select * from dbo.CM_COMM_PACKAGE_PRESENTATION WHERE COMM_PLAN_ID = '2000GFFCD0K4' AND STEP_ID = '2000ggv79rhr'
select * from cm_comm_package_collateral WHERE COMM_PLAN_ID = '2000GFFCD0K4' AND STEP_ID = '2000ggv79rhr'
