--B-19650 Sequences

CREATE SEQUENCE  "CCPA"."CONFIG_NAME_SEQ"  
MINVALUE 1 
NOMAXVALUE 
INCREMENT BY 1 
START WITH 1 
NOCACHE  
NOORDER  
NOCYCLE ;

CREATE SEQUENCE  "CCPA"."CS_ID_SEQ"  
MINVALUE 1 
NOMAXVALUE 
INCREMENT BY 1 
START WITH 1 
NOCACHE  
NOORDER  
NOCYCLE ;

CREATE SEQUENCE  "CCPA"."TZONE_ID_SEQ"  
MINVALUE 1 
NOMAXVALUE 
INCREMENT BY 1 
START WITH 1 
NOCACHE  
NOORDER  
NOCYCLE ;
